### ISSUE TITLE
[Feature Request] Limit max different resources per town level

### ISSUE THREAD

**Issue by Bibithom** [TownyAdvanced/TownyResources#59]
Hi ! I would suggest that we can in config add a maximum number of different resources discoverable. And possibly modify this limit with town-level.

For example town A is level 2, it cans have 4 max different resources, town B is level 4, it cans have 8 different resources.

Example of settings :
```yaml
# Max limit of resources, no town can have more than limit 
# set -1 to disable
overall_max_different_resources: <number>

# Put factor which multiply town-level to limit max different resources
# set -1 to disable
# example town_level_factor: 2 -> Your town level * 2 = max resources number (town level 2 - 2 * 2 = 4 max different resources)
town_level_factor: <number>
```
We really enjoy towny resources, this is a little feature that can mitigate some config not usinf daily extraction limit, it is up to you to take or not.

Thank's for your hard work, have a good day !
